# .github/workflows/finops-guardian.yml

name: FinOps Guardian

on:
  pull_request:
    paths:
      - 'ejemplo-terraform/**.tf'

jobs:
  cost-analysis:
    runs-on: ubuntu-latest
    
    # CORRECCIÓN: Definir el directorio de trabajo por defecto para todos los pasos.
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      # PASO DE DEPURACIÓN: Listar archivos para ver la estructura.
      - name: List files in workspace
        run: ls -R

      - name: Build FinOps Guardian CLI
        run: go build -o finops-guardian ./cmd/finops-guardian/

      # CORRECCIÓN: Forma más robusta de capturar la salida multilínea.
      - name: Run Guardian and capture output
        id: guardian_run
        run: |
          REPORT=$(./finops-guardian --file infracost-output.json)
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "report<<$EOF" >> $GITHUB_OUTPUT
          echo "$REPORT" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT

      - name: Print captured report
        run: |
          echo "--- Reporte Capturado ---"
          echo "${{ steps.guardian_run.outputs.report }}"
          echo "--------------------------"
