# .github/workflows/finops-guardian.yml (Versión Final, Simplificada y Correcta)

name: FinOps Guardian

on:
  pull_request:
    paths:
      - 'ejemplo-terraform/**.tf'

permissions:
  pull-requests: write

jobs:
  cost-analysis:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      # NO hay 'working-directory'. Los comandos se ejecutan en la raíz.

      - name: Download Go Modules
        run: go mod tidy

      - name: Build FinOps Guardian CLI
        run: go build -v -o finops-guardian ./cmd/finops-guardian/
      
      - name: Run Guardian and capture report
        id: guardian_run
        run: |
          REPORT=$(./finops-guardian --file infracost-output.json)
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "report<<$EOF" >> $GITHUB_OUTPUT
          echo "$REPORT" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT

      - name: Post report as PR comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `${{ steps.guardian_run.outputs.report }}`
            });
