# .github/workflows/finops-guardian.yml

# El nombre de nuestra Action, aparecer치 en la interfaz de GitHub.
name: FinOps Guardian

# La secci칩n 'on' define cu치ndo se ejecutar치 esta Action.
on:
  # Queremos que se active en cada 'pull_request'.
  pull_request:
    # Pero solo si los archivos modificados en la PR est치n dentro
    # de la carpeta 'ejemplo-terraform/' y terminan en '.tf'.
    # Esto evita ejecuciones innecesarias.
    paths:
      - 'ejemplo-terraform/**.tf'

# 'jobs' define una o m치s tareas a ejecutar.
jobs:
  # Definimos un 칰nico job llamado 'cost-analysis'.
  cost-analysis:
    # El tipo de m치quina virtual en la que se ejecutar치. 'ubuntu-latest' es com칰n y econ칩mico.
    runs-on: ubuntu-latest

    # 'steps' son los comandos que se ejecutan secuencialmente en el job.
    steps:
      # Paso 1: 'actions/checkout' es una action oficial de GitHub
      # que descarga tu c칩digo fuente en la m치quina virtual para que podamos usarlo.
      - name: Checkout code
        uses: actions/checkout@v4

      # Paso 2: Un simple paso para verificar que la action se est치 ejecutando.
      # Imprimir치 este mensaje en los logs de la Action.
      - name: Announce Guardian's arrival
        run: echo "游닉 FinOps Guardian se ha activado por un cambio en Terraform."
