# .github/workflows/finops-guardian.yml (Versión de Depuración)

name: FinOps Guardian (Debug Build)

on:
  pull_request:
    paths:
      - 'ejemplo-terraform/**.tf'

jobs:
  cost-analysis:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      # PASO DE DEPURACIÓN CRÍTICO
      - name: 1. Show Directory Structure
        run: |
          echo "--- Current working directory ---"
          pwd
          echo "--- Listing contents of the workspace (recursively) ---"
          ls -R
      
      # NUEVO ENFOQUE: Compilar con más información
      - name: 2. Attempt to Build with Verbose Output
        run: |
          echo "--- Attempting to build Go binary ---"
          # Usamos el flag -v para que Go nos diga qué está haciendo.
          go build -v -o finops-guardian ./cmd/finops-guardian/

      # Este paso solo se ejecutará si el build tiene éxito.
      - name: 3. Verify and Run
        run: |
          echo "--- Listing files after build to confirm binary exists ---"
          ls -l
          echo "--- Running FinOps Guardian ---"
          ./finops-guardian --file infracost-output.json
