name: FinOps Guardian - Cost Check

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  infracost:
    name: Infracost cost estimate
    runs-on: ubuntu-latest
    steps:
      - name: Check out base code
        uses: actions/checkout@v4
        with:
          # Required for Infracost to get the baseline
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Check out PR code
        uses: actions/checkout@v4
        with:
          # Required for Infracost to get the proposed changes
          path: pr

      # Esta es la única acción de Infracost que necesitamos.
      # Le decimos el path del PR y ella se encarga del resto.
      - name: Run Infracost
        uses: infracost/infracost-action@v2
        with:
          # El path del código del Pull Request
          path: pr/
          # La clave de API, pasada de forma segura
          api-key: ${{ secrets.INFRACOST_API_KEY }}
          # El comportamiento: crear un comentario nuevo o actualizar uno existente.
          behavior: update
