name: FinOps Guardian - Cost Check

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  infracost:
    name: Infracost cost estimate
    runs-on: ubuntu-latest
    steps:
      - name: Check out base code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Check out PR code
        uses: actions/checkout@v4
        with:
          path: pr

      # --- ¡LA CORRECCIÓN DEFINITIVA ESTÁ AQUÍ! ---
      # La ruta correcta es 'infracost/infracost-github-action@v2'
      - name: Run Infracost
        uses: infracost/infracost-github-action@v2
        with:
          path: pr/
          api-key: ${{ secrets.INFRACOST_API_KEY }}
          behavior: update
